### ISSUE TITLE
Minor Request: Can the progress bar be relocatable on the dashboard as a setting?

### ISSUE THREAD

**Issue by VIDGuide** [TFyre/bambu-farm#158]
2 of my printers have multi-AMS's and this pushes the progress/time-remaining box off the bottom of the screen for my dashboard. 
I'm less interested in the AMS status (though I do like having it there, I'd prefer not to have to turn it off in the .env), but I am very interested to see the progress bar at a glance. 

Would be nice if there was a config option that would put it up near the control buttons, or above the stream perhaps.

**Comment by VIDGuide** [comment]
#159 Added PR for a patch to handle this, if it's suitable to your style/intentions. 
Added an .env var to control position, "above-image", "below-image", "bottom" (default, current location)

**Comment by TFyre** [comment]
Closing this as the order can be configured using CSS [(readme.md)](https://github.com/TFyre/bambu-farm?tab=readme-ov-file#ordering-items-inside-printer-box):

```css
.dashboard-printer .image {
    order: 3;
}
.dashboard-printer .status {
    order: 4;
}
.dashboard-printer .filaments {
    order: 1;
}
```
