### ISSUE TITLE
Cannot work out how to get camera view on A1

### ISSUE THREAD

**Issue by TheCableGuy99** [TFyre/bambu-farm#232]
Hi,

I have the X1C's working and everything is fine including the camera but I cannot work out what I need to do different to get a new A1 printer live view working.

In bambu-web-env.txt everything is setup the same as the X1C's apart from the following line which specifies it's an "a1" instead:
`bambu.printers.myprinter3.model=a1`

I also noted that I couldn't see a "Lan Mode Live View" setting on the printer like the X1C so I'm hoping you can access the camera without having to disable cloud mode?

Please could I get some guidance? 

Thanks.

**Comment by TFyre** [comment]
> In bambu-web-env.txt everything is setup the same as the X1C's apart from the following line which specifies it's an "a1" instead:

If live-view is enabled, please disable/remove it, since its not available for the A1, only X1*'s

Refer to this section: https://github.com/TFyre/bambu-farm/tree/main?tab=readme-ov-file#live-view

It should NOT have the following line:
```
bambu.printers.myprinter3.stream.live-view=true
```

**Comment by TFyre** [comment]
> I'm wondering if there's no way to get the A1 camera view to work can I get an RTSP stream to work for that printer from another camera?

Yes, this is possible, refer to the live-view section: https://github.com/TFyre/bambu-farm/tree/main?tab=readme-ov-file#live-view

You can configure the docker container to stream from any RTSP camera and allow you to serve it via MediaMTX

**Comment by TFyre** [comment]
Using your own camera stream is fairly involved. Browsers generally cannot display rtsp directly from a camera. You need the appropriate settings to transcode it from rtsp to something that the browser can handle.

You need something like this:
https://github.com/TFyre/bambu-farm/blob/main/docker/bambu-liveview/example%20-%20compose.yml#L40-L49

Which also includes something like this:
https://github.com/TFyre/bambu-farm/blob/main/docker/bambu-liveview/common-liveview.yml

In a nutshell, it needs to have a docker container that uses ffmpeg to read the rtsp from the camera, transcode it and publishes it to mediamtx. Once this is done, the browser can easily stream the camera

**Comment by TFyre** [comment]
Do not edit/change common-liveview.yml, because that will break all your printers

compose.yml should have something like this for printer3:
```
    printer3:
        extends:
            file: common-liveview.yml
            service: liveview
        depends_on:
            - mediamtx
        environment:
            PRINTER_HOST: FIXME_this_is_the_webcam_ip
            PRINTER_ID: FIXME_this_is_my_printer_id
            PRINTER_USER: FIXME_this_is_the_webcam_username
            PRINTER_ACCESS_CODE: FIXME_this_is_the_webcam_password
            PRINTER_PORT: 554
            PRINTER_URL: /unicast
```

bambu-web-env.txt remove the stream.url:
```
#bambu.printers.myprinter3.stream.url=rtsp://user:pass@192.168.xxx.xxx:554/unicast
```
